---
title: "Gov 50 Final Project"
author: "Hazel Koh"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to compliance with International Court of Justice decisions. I would like to determine whether a state's level of democracy, their government's ideology, or their aggregate power has a treatment effect on their willingness to comply with the Court's decisions. I will decide which of these treatment variables I would like to focus on based on the data I'm able to find. 


## Research Proposal

Are democracies more likely to comply with international law? I hope to answer this research question by analyzing democratic states' compliance with International Court of Justice (ICJ) decisions. I hypothesize that democracies have a higher record of compliance than their autocratic counterparts. My hypothesis stems from the tendency of democracies to value justice and respect the rule of law more than autocracies. Democracies might also face more pressure to comply, as they have greater accountability to their publics through transparency. My sample is comprised of ICJ cases that have occurred from 1947 to 2018. My unit of analysis is an ICJ case. The explanatory variable of interest is whether a state is a democracy or an autocracy according to their Polity score. The variable is coded = 1 for democracies (+6 to +10) and =0 for anocracies and autocracies (-10 to +5). For the purposes of this study, anocracies will be coded as autocracies. My outcome variable is a state's compliance rate. This variable is measured from Tom Ginsburg's data on ICJ compliance found in the Comparative Constitutions Project's dataset. I will calculate the compliance rate of states by dividing the number of times they have complied with an ICJ judgement by the number of times they have been required them to comply to a ruling. I would find support for my hypothesis if I observe a greater compliance rate by democracies and a positive coefficient when I run my regression of the compliance rate on the democracy variable. If I find that there is a negative or no relationship between these two variables, I will have to re-evaluate my hypothesis. 
